import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { forwardRef, useImperativeHandle } from 'react';
import { useTranslation } from 'react-i18next';
import MonthlyRevenueChart from '../../components/MonthlyRevenueChart';
import { TfiPackage } from 'react-icons/tfi';
import { Truck } from 'lucide-react';
import { FiCheckSquare, FiDollarSign } from 'react-icons/fi';
const OperationsOverview = forwardRef(({ metricsData, isLoading, onRefresh }, ref) => {
    const { t } = useTranslation();
    // Expose methods cho parent component (similar to AdminDashboard)
    useImperativeHandle(ref, () => ({
        updateMetrics: onRefresh
    }), [onRefresh]);
    return (_jsxs("div", { className: "space-y-4 md:space-y-6", children: [_jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-6", children: [_jsxs("div", { className: "bg-white/30 backdrop-blur-lg border border-white/30 rounded-2xl p-3 md:p-6 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105", children: [_jsxs("div", { className: "flex items-center justify-between mb-2 md:mb-4", children: [_jsx("h3", { className: "text-gray-700 font-medium text-xs md:text-base", children: t('dashboard.operations.overview.todaysOrders', "Today's Orders") }), _jsx("span", { className: "text-xl md:text-2xl", children: _jsx(TfiPackage, { size: window.innerWidth < 768 ? 20 : 24, color: "#3b82f6" }) })] }), isLoading ? (_jsxs("div", { className: "animate-pulse", children: [_jsx("div", { className: "h-6 md:h-8 bg-gray-200 rounded mb-1 md:mb-2" }), _jsx("div", { className: "h-3 md:h-4 bg-gray-200 rounded w-3/4" })] })) : (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-2xl md:text-3xl font-bold text-gray-800", children: metricsData.todayOrders.count }), _jsxs("p", { className: `text-xs md:text-sm mt-1 md:mt-2 ${metricsData.todayOrders.trend === 'increase' ? 'text-green-600' :
                                            metricsData.todayOrders.trend === 'decrease' ? 'text-red-600' : 'text-gray-600'}`, children: [metricsData.todayOrders.changePercent > 0 ? '+' : '', metricsData.todayOrders.changePercent, "% ", t('dashboard.operations.overview.comparedToYesterday', 'compared to yesterday')] })] }))] }), _jsxs("div", { className: "bg-white/30 backdrop-blur-lg border border-white/30 rounded-2xl p-3 md:p-6 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105", children: [_jsxs("div", { className: "flex items-center justify-between mb-2 md:mb-4", children: [_jsx("h3", { className: "text-gray-700 font-medium text-xs md:text-base", children: t('dashboard.operations.overview.activeVehicles', 'Active Vehicles') }), _jsx("span", { className: "text-xl md:text-2xl", children: _jsx(Truck, { size: window.innerWidth < 768 ? 20 : 24, color: "#f59e0b" }) })] }), isLoading ? (_jsxs("div", { className: "animate-pulse", children: [_jsx("div", { className: "h-6 md:h-8 bg-gray-200 rounded mb-1 md:mb-2" }), _jsx("div", { className: "h-3 md:h-4 bg-gray-200 rounded w-3/4" })] })) : (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-2xl md:text-3xl font-bold text-gray-800", children: metricsData.activeVehicles.ratio }), _jsxs("p", { className: "text-gray-600 text-xs md:text-sm mt-1 md:mt-2", children: [metricsData.activeVehicles.percentage, "% ", t('dashboard.operations.overview.ofTotalVehicles', 'of total vehicles')] })] }))] }), _jsxs("div", { className: "bg-white/30 backdrop-blur-lg border border-white/30 rounded-2xl p-3 md:p-6 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105", children: [_jsxs("div", { className: "flex items-center justify-between mb-2 md:mb-4", children: [_jsx("h3", { className: "text-gray-700 font-medium text-xs md:text-base", children: t('dashboard.operations.overview.todaysRevenue', "Today's Revenue") }), _jsx("span", { className: "text-xl md:text-2xl", children: _jsx(FiDollarSign, { size: window.innerWidth < 768 ? 20 : 24, color: "#10b981" }) })] }), isLoading ? (_jsxs("div", { className: "animate-pulse", children: [_jsx("div", { className: "h-6 md:h-8 bg-gray-200 rounded w-20 md:w-24 mb-1 md:mb-2" }), _jsx("div", { className: "h-3 md:h-4 bg-gray-200 rounded w-24 md:w-32" })] })) : (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-2xl md:text-3xl font-bold text-gray-800", children: metricsData.revenueData.amount }), _jsxs("p", { className: `text-xs md:text-sm mt-1 md:mt-2 ${metricsData.revenueData.trend === 'increase' ? 'text-green-600' :
                                            metricsData.revenueData.trend === 'decrease' ? 'text-red-600' : 'text-gray-600'}`, children: [metricsData.revenueData.trend === 'increase' ? '+' :
                                                metricsData.revenueData.trend === 'decrease' ? '-' : '', metricsData.revenueData.changePercent.toFixed(1), "% ", t('dashboard.operations.overview.comparedToYesterday', 'compared to yesterday')] })] }))] }), _jsxs("div", { className: "bg-white/30 backdrop-blur-lg border border-white/30 rounded-2xl p-3 md:p-6 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105", children: [_jsxs("div", { className: "flex items-center justify-between mb-2 md:mb-4", children: [_jsx("h3", { className: "text-gray-700 font-medium text-xs md:text-base", children: t('dashboard.operations.overview.completedOrders', 'Completed Orders') }), _jsx("span", { className: "text-xl md:text-2xl", children: _jsx(FiCheckSquare, { size: window.innerWidth < 768 ? 20 : 24, color: "#8b5cf6" }) })] }), isLoading ? (_jsxs("div", { className: "animate-pulse", children: [_jsx("div", { className: "h-6 md:h-8 bg-gray-200 rounded w-20 md:w-24 mb-1 md:mb-2" }), _jsx("div", { className: "h-3 md:h-4 bg-gray-200 rounded w-24 md:w-32" })] })) : (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-2xl md:text-3xl font-bold text-gray-800", children: metricsData.performanceData.count }), _jsxs("p", { className: `text-xs md:text-sm mt-1 md:mt-2 ${metricsData.performanceData.trend === 'increase' ? 'text-green-600' :
                                            metricsData.performanceData.trend === 'decrease' ? 'text-red-600' : 'text-gray-600'}`, children: [metricsData.performanceData.trend === 'increase' ? '+' :
                                                metricsData.performanceData.trend === 'decrease' ? '-' : '', metricsData.performanceData.changePercent.toFixed(1), "% ", t('dashboard.operations.overview.comparedToYesterday', 'compared to yesterday')] })] }))] })] }), _jsx("div", { className: "w-full", children: _jsx(MonthlyRevenueChart, { onRefreshAll: onRefresh }) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6" })] }));
});
OperationsOverview.displayName = 'OperationsOverview';
export default OperationsOverview;
