import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { memo } from "react";
import { useTranslation } from 'react-i18next';
import { Search, Filter, Plus } from "lucide-react";
const SearchAndFilter = memo(({ searchTerm, statusFilter, onSearch, onStatusFilter, onToggleAddForm, showAddForm, resultsCount, totalCount }) => {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "bg-white/30 hover:bg-white/40 rounded-xl p-6 shadow-lg", children: [_jsxs("div", { className: "flex flex-col lg:flex-row gap-4 items-start lg:items-center justify-between mb-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900", children: t('fleet.search.title', 'Vehicle Management') }), _jsx("p", { className: "text-gray-600 mt-1", children: t('fleet.search.subtitle', 'Search and filter vehicle list') })] }), _jsxs("button", { onClick: onToggleAddForm, className: "bg-violet-600 hover:bg-violet-700 text-white px-6 py-2 rounded-lg font-medium transition-colors duration-200 flex items-center gap-2", children: [_jsx(Plus, { size: 20 }), showAddForm ? t('fleet.search.hideForm', 'Hide Form') : t('fleet.form.addVehicle', 'Add Vehicle')] })] }), _jsxs("div", { className: "flex flex-col md:flex-row gap-4 mb-6", children: [_jsxs("div", { className: "flex-1 relative", children: [_jsx("input", { type: "text", placeholder: t('fleet.search.placeholder', 'Search by license plate, brand, model, driver...'), value: searchTerm, onChange: (e) => onSearch(e.target.value), className: "w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition-colors" }), _jsx(Search, { size: 20, className: "absolute left-3 top-3.5 text-gray-400" })] }), _jsxs("div", { className: "relative", children: [_jsxs("select", { value: statusFilter, onChange: (e) => onStatusFilter(e.target.value), className: "appearance-none bg-white border border-gray-300 rounded-lg px-4 py-3 pr-8 focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition-colors", children: [_jsx("option", { value: "all", children: t('fleet.search.allStatus', 'All Status') }), _jsx("option", { value: "AVAILABLE", children: t('dashboard.fleet.status.available') }), _jsx("option", { value: "IN_USE", children: t('dashboard.fleet.status.inUse') }), _jsx("option", { value: "MAINTENANCE", children: t('dashboard.fleet.status.underMaintenance') }), _jsx("option", { value: "MAINTENANCE_PENDING", children: t('dashboard.fleet.status.needMaintenance') })] }), _jsx(Filter, { size: 20, className: "absolute right-2 top-3.5 text-gray-400 pointer-events-none" })] })] })] }));
});
SearchAndFilter.displayName = "SearchAndFilter";
export default SearchAndFilter;
