import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function OrderDetailModal({ open, onClose, orderItem, products, deliveryFee, productsPage = 0, productsTotalPages = 1, onProductsPageChange }) {
    if (!open || !orderItem)
        return null;
    // Debug log để kiểm tra dữ liệu truyền vào modal
    console.log('🔍 OrderDetailModal - orderItem received:', orderItem);
    console.log('🔍 OrderDetailModal - orderItem.addressDetail:', orderItem.addressDetail);
    // Lấy thông tin người nhận từ orderItem.address nếu có dạng object
    let contactName = undefined;
    let contactPhone = undefined;
    // Lấy từ orderItem.address nếu có
    if (orderItem && typeof orderItem.address === 'object' && orderItem.address !== null) {
        contactName = orderItem.address.contactName;
        contactPhone = orderItem.address.contactPhone;
    }
    // Nếu không có, lấy từ orderItem.order.address nếu có
    if ((!contactName || !contactPhone) && orderItem.order?.address) {
        contactName = orderItem.order.address.contactName;
        contactPhone = orderItem.order.address.contactPhone;
    }
    // Ưu tiên addressDetail từ props, nếu không có thì dùng từ address object hoặc order.address
    const addressDetail = orderItem.addressDetail || {
        contactName: contactName || undefined,
        contactPhone: contactPhone || undefined
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-white rounded-lg p-6 max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto", children: [_jsxs("div", { className: "flex justify-between items-center mb-4", children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900", children: "Chi ti\u1EBFt \u0111\u01A1n h\u00E0ng" }), _jsx("button", { onClick: onClose, className: "text-gray-500 hover:text-gray-700 text-2xl", children: "\u00D7" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "M\u00E3 \u0111\u01A1n" }), _jsx("p", { className: "text-gray-900", children: orderItem.code })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Kh\u00E1ch h\u00E0ng" }), _jsx("p", { className: "text-gray-900", children: orderItem.customer })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Tr\u1EA1ng th\u00E1i" }), _jsx("p", { className: "text-gray-900", children: orderItem.status })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Ng\u00E0y t\u1EA1o" }), _jsx("p", { className: "text-gray-900", children: orderItem.date })] })] }), (addressDetail?.contactName || addressDetail?.contactPhone) && (_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [addressDetail?.contactName && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "T\u00EAn ng\u01B0\u1EDDi nh\u1EADn" }), _jsx("p", { className: "text-gray-900", children: addressDetail.contactName })] })), addressDetail?.contactPhone && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "S\u1ED1 \u0111i\u1EC7n tho\u1EA1i ng\u01B0\u1EDDi nh\u1EADn" }), _jsx("p", { className: "text-gray-900", children: addressDetail.contactPhone })] }))] })), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "\u0110\u1ECBa ch\u1EC9 giao h\u00E0ng" }), _jsx("p", { className: "text-gray-900", children: typeof orderItem.address === 'object' && orderItem.address !== null
                                        ? orderItem.address.address
                                        : orderItem.address })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "L\u1ED9 tr\u00ECnh" }), _jsxs("div", { className: "text-gray-900", children: [_jsxs("p", { children: [_jsx("strong", { children: "T\u1EEB:" }), " ", orderItem.from] }), _jsxs("p", { children: [_jsx("strong", { children: "\u0110\u1EBFn:" }), " ", orderItem.to, typeof orderItem.address === 'object' && orderItem.address?.city ? ", " + orderItem.address.city : ""] })] })] }), products && products.length > 0 && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "S\u1EA3n ph\u1EA9m" }), _jsxs("table", { className: "min-w-full text-sm mt-2", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { className: "text-left", children: "T\u00EAn s\u1EA3n ph\u1EA9m" }), _jsx("th", { className: "text-left", children: "S\u1ED1 l\u01B0\u1EE3ng" }), _jsx("th", { className: "text-left", children: "Kh\u1ED1i l\u01B0\u1EE3ng" }), _jsx("th", { className: "text-left", children: "Th\u1EC3 t\u00EDch" }), _jsx("th", { className: "text-left", children: "H\u00E0ng d\u1EC5 v\u1EE1" }), _jsx("th", { className: "text-left", children: "Ph\u00ED giao h\u00E0ng" }), _jsx("th", { className: "text-left", children: "Ghi ch\u00FA" })] }) }), _jsx("tbody", { children: products.map(item => (_jsxs("tr", { children: [_jsx("td", { children: item.product?.name }), _jsx("td", { children: item.quantity }), _jsx("td", { children: item.product?.weight !== undefined ? item.product.weight : "" }), _jsx("td", { children: item.product?.volume !== undefined ? item.product.volume : "" }), _jsx("td", { children: item.product?.fragile !== undefined ? (item.product.fragile ? "Có" : "Không") : "" }), _jsx("td", { children: item.shippingFee
                                                            ? Number(String(item.shippingFee).replace(/,/g, "")).toLocaleString() + " đ"
                                                            : "" }), _jsx("td", { children: item.notes || "" })] }, item.id))) })] }), productsTotalPages > 1 && onProductsPageChange && (_jsxs("div", { className: "flex justify-center items-center gap-2 mt-4", children: [_jsx("button", { onClick: () => onProductsPageChange(productsPage - 1), disabled: productsPage === 0, className: "px-3 py-1 rounded bg-blue-100 hover:bg-blue-200 disabled:opacity-50 text-blue-700 font-semibold text-sm", children: "< Tr\u01B0\u1EDBc" }), _jsxs("span", { className: "text-sm text-gray-600", children: ["Trang ", productsPage + 1, " / ", productsTotalPages] }), _jsx("button", { onClick: () => onProductsPageChange(productsPage + 1), disabled: productsPage >= productsTotalPages - 1, className: "px-3 py-1 rounded bg-blue-100 hover:bg-blue-200 disabled:opacity-50 text-blue-700 font-semibold text-sm", children: "Ti\u1EBFp >" })] }))] })), typeof deliveryFee === "number" && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Ph\u00ED giao h\u00E0ng" }), _jsxs("p", { className: "text-gray-900", children: [deliveryFee.toLocaleString(), " \u0111"] })] })), orderItem.note && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Ghi ch\u00FA" }), _jsx("p", { className: "text-gray-900", children: orderItem.note })] })), orderItem.description && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "M\u00F4 t\u1EA3" }), _jsx("p", { className: "text-gray-900", children: orderItem.description })] })), orderItem.assignedVehicle && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "Xe \u0111\u01B0\u1EE3c g\u00E1n" }), _jsxs("p", { className: "text-gray-900", children: [orderItem.assignedVehicle.licensePlate, " - ", orderItem.assignedVehicle.vehicleType] })] })), orderItem.currentDriver && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700", children: "T\u00E0i x\u1EBF" }), _jsx("p", { className: "text-gray-900", children: orderItem.currentDriver.fullName || orderItem.currentDriver.username })] }))] }), _jsx("div", { className: "flex justify-end mt-6", children: _jsx("button", { onClick: onClose, className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "\u0110\u00F3ng" }) })] }) }));
}
